# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ad1ff3cc1021d42d1cacbd2f4d79ec9ea06a4c19dbbfe774b49c09a341898d375e066647be2b26ddd1f11b7981d3b5fc59cb0e100f38640051af6516070958

test:
  secret_key_base: 4f154d6cb53807e69d2def4a69fe264e1aef3746400ecaa8facfc79e6767a373215f5e7d7deb7e65eb8be20861e80efa0e930c24c97f513a59d8cb244a7d320a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
